### ISSUE TITLE
Another mirror

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [TheBobPony/getwindows11.tech#1]
http://69.51.24.27/Windows%2011/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Comment by TheBSODAndWSODFan** [comment]
feel free to subscribe me here https://www.youtube.com/channel/UC_d3FuquZ1z6UqVrXAiXEWg

**Comment by TheBobPony** [comment]
What's with the direct IP and will this be up for awhile?

**Comment by TheBSODAndWSODFan** [comment]
idk i found that link on collab vm and it worked

**Comment by TheBobPony** [comment]
Link will be added in! _Thanks for contributing!_
