### ISSUE TITLE
[BROKEN] omame.tech temporarily down

### ISSUE THREAD

**Issue by omaemae** [TheBobPony/getwindows11.tech#104]
**Mirror**
omame.tech

**Problem**  
i temporarily took down the mirror because it was causing such high traffic that nginx started erroring out because it wouldn't open files (which means it opened 500k+ files???)

**Notes**  
temporarily down ig

**Comment by TheBobPony** [comment]
Here's an idea, make the page password protected or use cloudflare under attack mode.

**Comment by omaemae** [comment]
> Here's an idea, make the page password protected or use cloudflare under attack mode.

i could also try raising the limit, which sounds like a good solution to me

**Comment by TheBobPony** [comment]
> > Here's an idea, make the page password protected or use cloudflare under attack mode.
> 
> i could also try raising the limit, which sounds like a good solution to me

And you could use page rules to set the link to be under attack mode too.

**Comment by omaemae** [comment]
back up, will; re-open if more issues arise
