### ISSUE TITLE
another windows 11 iso get from indonesian website

### ISSUE THREAD

**Issue by TheBSODAndWSODFan** [TheBobPony/getwindows11.tech#2]
https://uptobox.com/3r679hy6czzi
https://mega.nz/file/ofpk1QoQ#7ppsfplKjS_ibJ1zYUMeKfhcE5ZjkYUvMMVbpqi8Y70
https://www.mediafire.com/file/fln9mkvok3o29bh/%255Bgigapurbalingga.net%255D_w11.rar/file
https://usersdrive.com/31othqyd233n.html

Taken From This Website (Are Link Im Included Already Bypassed using Universal Bypass)
https://gigapurbalingga.net/download-windows-11/

feel free to subscribe me :) 
https://www.youtube.com/channel/UC_d3FuquZ1z6UqVrXAiXEWg

**Comment by TheBobPony** [comment]
Can you please submit a pull request with the links added in, would make everything so much easier! Thanks.

**Comment by TheBSODAndWSODFan** [comment]
sorry idk how to use github
