### ISSUE TITLE
[NEW ] Added Onedrive Mirror

### ISSUE THREAD

**Issue by anhieu2010** [TheBobPony/getwindows11.tech#33]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
https://1drv.ms/u/s!AkAfYcdXb78RgQA4d1zx6a8_oYwY?e=fSZa9D

**Type**
Onedrive  1 URL

**Notes**
Fast speed, unlimited downloads, needed login

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by tran1903alt** [comment]
Why Onedrive? This thing can be deleted my MS

**Comment by TheBobPony** [comment]
> Why Onedrive? This thing can be deleted my MS

This, seems like OneDrive uploads are the quickest ones to get deleted.

**Comment by TheBobPony** [comment]
Okay, seems to be taken down. _Not surprised, considering Microsoft owns OneDrive..._
