### ISSUE TITLE
[NEW] Added Onedrive 2 Mirror

### ISSUE THREAD

**Issue by anhieu2010** [TheBobPony/getwindows11.tech#34]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
https://minhduc-my.sharepoint.com/:u:/g/personal/windows11_onedrive5tb_com/ERo5-hgzxAhNiTwBFXBW8hIB2J53CCULr52YBbAEGRZltg?e=kcZbfE

**Type**
Onedrive URL

**Notes**
Fast speed, unlimited downloads, no needed login

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by sysdotini** [comment]
Doesn't exist anymore.
