### ISSUE TITLE
[NEW] Added Koofr Mirror

### ISSUE THREAD

**Issue by anhieu2010** [TheBobPony/getwindows11.tech#35]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
https://k00.fr/windows11iso

**Type**
app.koofr.net URL

**Notes**
Fast speed, unlimited downloads, no needed login

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by sysdotini** [comment]
This mirror already exists.
