### ISSUE TITLE
[NEW] Added MediaFire Link

### ISSUE THREAD

**Issue by 101happy** [TheBobPony/getwindows11.tech#40]
**URL**
https://www.mediafire.com/file/a3rb9tnrzb02s8b/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso/file

**Type**
Normal URL

**Notes**
Original ISO

**Comment by rexjohannes** [comment]
taken down https://rexum.skids-ht.ml/sx3AO22jIxE
