### ISSUE TITLE
[BROKEN] DMCA Button leads to a rick role

### ISSUE THREAD

**Issue by Snornite** [TheBobPony/getwindows11.tech#41]
Tile. This is completely unacceptable. For more contact, please contact me at james.amith@microsoft.com

Thanks
James

**Comment by PolishNeko** [comment]
> Tile. This is completely unacceptable. For more contact, please contact me at [james.amith@microsoft.com](mailto:james.amith@microsoft.com)
> 
> Thanks
> James

Are you getting serious? I wonder if you are the real employee at Microsoft

**Comment by PolishNeko** [comment]
Very funny issue Jack

**Comment by Snornite** [comment]
> > Tile. This is completely unacceptable. For more contact, please contact me at [james.amith@microsoft.com](mailto:james.amith@microsoft.com)
> > Thanks
> > James
> 
> Are you getting serious? I wonder if you are the real employee at Microsoft

https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by 101happy** [comment]
Very Funny

**Comment by 101happy** [comment]
Funny Funny

**Comment by 101happy** [comment]
Its totally not a joke

**Comment by Snornite** [comment]
> Its totally not a joke

james.amith@microsoft.com Please contact me. https://www.youtube.com/watch?v=dQw4w9WgXcQ Here is proof of me being a Microsoft employee in the legal department.

**Comment by 101happy** [comment]
Very Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny Funny

**Comment by utf-4096** [comment]
get a life jack

**Comment by Snornite** [comment]
This is a joke. Have a nice day :))))

**Comment by omaemae** [comment]
> This is a joke. Have a nice day :))))

anyone with a functioning set of eyes or ears could see that you're not a microsoft employee
