### ISSUE TITLE
[BROKEN] General mirrors are broken

### ISSUE THREAD

**Issue by WitherCubes** [TheBobPony/getwindows11.tech#42]
**Mirror**
- [ 1fichier.com (by rexum) ](https://1fichier.com/?ylsqj52oxe9y8jy9otng)
- [ megaup.net (by zlew-chan)]( https://megaup.net/1Dq24/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso)

**Problem**
The mirrors are broken, they don't work.

**Notes**
Please remove it because these links don't work

**Comment by rexjohannes** [comment]
both links working

![image](https://user-images.githubusercontent.com/53578137/122645840-b1f75d00-d11c-11eb-9dde-af2d8246ed62.png)
![image](https://user-images.githubusercontent.com/53578137/122645846-bcb1f200-d11c-11eb-8e13-0a24d675649d.png)

**Comment by TheBobPony** [comment]
Both links are confirmed working, closing issue now.

**Comment by WitherCubes** [comment]
Sorry, just now found out that my country has blocked these links, so they didn't work.
