### ISSUE TITLE
[NEW] Just a mirror

### ISSUE THREAD

**Issue by veastdottk** [TheBobPony/getwindows11.tech#43]
**URL**
https://veast.tk/Mirror/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Type**
Normal URL

**Notes**
Mirror hosted on my website, Original ISO

**Comment by TheBobPony** [comment]
Where is this hosted on? Is this self-hosted from a residential?

**Comment by veastdottk** [comment]
Selfhosted from a resedential

**Comment by veastdottk** [comment]
lads my domain got marked for fraud and it's probably because of the iso, i'm gonna have to close this

**Comment by omaemae** [comment]
> lads my domain got marked for fraud and it's probably because of the iso, i'm gonna have to close this

freenom moment

**Comment by veastdottk** [comment]
yeah i'm pretty pissed
