### ISSUE TITLE
[BROKEN] Mirror 404ing

### ISSUE THREAD

**Issue by veastdottk** [TheBobPony/getwindows11.tech#44]
**Mirror**
http://69.51.24.27/Windows%2011/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Problem**
[404 Not Found](https://imgur.com/a/1FVF3gY)

**Notes**
Ask the person who uploaded to reupload, or delete this mirror

**Comment by TheBobPony** [comment]
Removing it now, thanks.
