### ISSUE TITLE
[NEW] Pixeldrain

### ISSUE THREAD

**Issue by Azert58** [TheBobPony/getwindows11.tech#47]
**URL** : [https://pixeldrain.com/u/8vAQeWdy](https://pixeldrain.com/u/8vAQeWdy)

**Type** : normal URL

**Notes** : Pixeldrain File Hosting , Original ISO untouched

**Comment by rexjohannes** [comment]
why closed?

**Comment by Azert58** [comment]
forgot to tag new-mirror
[up here](https://github.com/TheBobPony/getwindows11.tech/issues/48)
