### ISSUE TITLE
[NEW] Xunlei

### ISSUE THREAD

**Issue by BreadIsPan** [TheBobPony/getwindows11.tech#49]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
URL：https://pan.xunlei.com/s/VMcUApJUT_lmVsN6zLCefkNfA1
PASS：b9ur

**Type**
Normal

**Notes**
China server, need register and download xunlei app

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by sysdotini** [comment]
We're only allowing open downloads - meaning that no registration needs to be done to get the file right now.
