### ISSUE TITLE
[NEW] Mirror of ISO in my website

### ISSUE THREAD

**Issue by WitherCubes** [TheBobPony/getwindows11.tech#54]
**URL**
https://withercubes.xyz/windows-11

**Type**
This is a normal URL.

**Notes**
Please use this as a backup mirror because this mirror maybe slow.

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by krystian3w** [comment]
See #109 / #113
