### ISSUE TITLE
[NEW] Mediafire Mirror

### ISSUE THREAD

**Issue by Beau2222** [TheBobPony/getwindows11.tech#56]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**https://www.mediafire.com/file/02digg9ahx29hdo/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso/file**

**Normal Url**
Btw my name is Sparklingtube if you guys upload it to the site

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by 101happy** [comment]
Not working https://imgur.com/a/OOT17ra

**Comment by 101happy** [comment]
Please post the direct link to the download

**Comment by Beau2222** [comment]
> Not working https://imgur.com/a/OOT17ra

Bruh wth why is it in violation lol weird

**Comment by Beau2222** [comment]
> Not working https://imgur.com/a/OOT17ra

Fixed https://www.mediafire.com/file/02digg9ahx29hdo/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Comment by veastdottk** [comment]
> Fixed https://www.mediafire.com/file/02digg9ahx29hdo/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

![image](https://user-images.githubusercontent.com/86145902/122652294-11993c80-d10c-11eb-9f47-01df814764e2.png)

**Comment by sysdotini** [comment]
Mirror no longer exists.
