### ISSUE TITLE
[NEW] Google Drive mirror

### ISSUE THREAD

**Issue by Heavy0331** [TheBobPony/getwindows11.tech#57]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
https://drive.google.com/file/d/1aPRE9Tclf4Ldri-sewXG00E0MtGeNhQz/view?usp=sharing

**Type**
normal

**Notes**
Do you have any additional notes to have on the website?

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by sysdotini** [comment]
Added earlier.
