### ISSUE TITLE
New Mirror

### ISSUE THREAD

**Issue by nabeelshaikh7** [TheBobPony/getwindows11.tech#69]
# Important

Before requesting to have a mirror added, be sure you view our [contribution][contributing] guidelines.

**URL**
https://downloads.ufhc.live/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Type**
normal URL

**Notes**
Do you have any additional notes to have on the website?

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by sysdotini** [comment]
Added.
