### ISSUE TITLE
[NEW] linode direct webserver

### ISSUE THREAD

**Issue by Leo-Is-Chaos** [TheBobPony/getwindows11.tech#72]
**URL**
http://173.255.206.199/Downloads/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso

**Type**
URL (clearnet)

**Notes**
hosted on Linode with a gigabit connection downloads at around 12 MB/S. If their is issues leave a comment and I will try to check for now.

**Comment by GhostSlayer** [comment]
![image](https://user-images.githubusercontent.com/51095261/122968705-81b9f380-d394-11eb-8b03-84b0dba139b4.png)

**Comment by Leo-Is-Chaos** [comment]
I have been playing around with the server so here is the new link
[http://173.255.206.199/Downloads/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso](url)
