### ISSUE TITLE
[BROKEN] mega.nz

### ISSUE THREAD

**Issue by Slaf2** [TheBobPony/getwindows11.tech#77]
**Mirror**
https://mega.nz/file/sz4kBSIY#80AblBSafePAIe39aPvenp1wewATw41xPDdAMxUl8hg

**Problem**
The Mirror got deleted

**Notes**
Any notes you'd like us to have

**Comment by sysdotini** [comment]
Removed in https://github.com/TheBobPony/getwindows11.tech/commit/93dab736e45d24cb3b6a2c2ddd5c3d47faaaf97c
