### ISSUE TITLE
[BROKEN] mega.nz & google drive

### ISSUE THREAD

**Issue by lukgth** [TheBobPony/getwindows11.tech#78]
**Mirror**
Provide the troublesome mirror name (or URL).
https://mega.nz/file/sz4kBSIY#80AblBSafePAIe39aPvenp1wewATw41xPDdAMxUl8hg
https://schacweb.com/isos/Win11.iso
https://tusfiles.com/xn67yl42dnyz
https://nl4950.dediseedbox.com/share/share.php?uh=am5zeXN0ZW1z&s=qm0WbzhY7CPep9kVoby79lN31hER7LZF
https://drive.google.com/u/0/uc?id=1aPRE9Tclf4Ldri-sewXG00E0MtGeNhQz&export=download

**Problem**
Either DMCA'd or just not working.

**Notes**
None.

**Comment by sysdotini** [comment]
Removed in https://github.com/TheBobPony/getwindows11.tech/commit/93dab736e45d24cb3b6a2c2ddd5c3d47faaaf97c
