### ISSUE TITLE
[NEW] New Mirror

### ISSUE THREAD

**Issue by imrolii** [TheBobPony/getwindows11.tech#79]
**URL**
https://ia801503.us.archive.org/25/items/win11build21996/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us%20%281%29.iso

**Type**
Normal URL

**Notes**
- Since archive.org is slow, I recommend using FDM or IDM to increase the speed.

**Comment by imrolii** [comment]
#

**Comment by sysdotini** [comment]
This already exists as archive.org-1.md.
