### ISSUE TITLE
[BROKEN] koofr

### ISSUE THREAD

**Issue by imrolii** [TheBobPony/getwindows11.tech#80]
**Mirror**
https://app.koofr.net/links/fb4fb4bf-cd76-4793-b9d9-dade5f7016a8

**Problem**
When attempting to download, the site displays a copyright infringement error.

**Notes**
![Screenshot](https://user-images.githubusercontent.com/79724190/123119546-8980a300-d43b-11eb-8e31-da61586d5668.png)

**Comment by sysdotini** [comment]
This seems to still be working as of now.

Reopen the issue if it's taken down again

**Comment by BowserLover32** [comment]
yeah its gone 
![image](https://user-images.githubusercontent.com/40863838/123169237-02d1c300-d447-11eb-8e56-08dc44d81a66.png)
