### ISSUE TITLE
[NEW] OneDrive

### ISSUE THREAD

**Issue by nguyenthienminh** [TheBobPony/getwindows11.tech#89]
**URL**
https://chundiranganay-my.sharepoint.com/personal/huuysac95_crpolytechnic_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhuuysac95%5Fcrpolytechnic%5Fin%2FDocuments%2Fitthegioi%2Ecom%2FWIN%2FWIN%2011%2FWindows%2D11%2Eiso&parent=%2Fpersonal%2Fhuuysac95%5Fcrpolytechnic%5Fin%2FDocuments%2Fitthegioi%2Ecom%2FWIN%2FWIN%2011&originalPath=aHR0cHM6Ly9jaHVuZGlyYW5nYW5heS1teS5zaGFyZXBvaW50LmNvbS86dTovZy9wZXJzb25hbC9odXV5c2FjOTVfY3Jwb2x5dGVjaG5pY19pbi9FZEVzWGhSbml5UkFpdEhKT3RoakV5MEJUQU9QaXZpMzRzdE1tTjJCYkFEQjR3P3J0aW1lPWRnSVYyZk0yMlVn

**Type**
This is a normal Onedrive URL.

**Notes**
No

[contributing]: https://github.com/thebobpony/getwindows11.tech/blob/main/.github/CONTRIBUTING.md "CONTRIBUTING GUIDELINES"

**Comment by krystian3w** [comment]
logon required

**Comment by TheBobPony** [comment]
Still requires login, closing issue.
