### ISSUE TITLE
Is this legal?

### ISSUE THREAD

**Issue by Dogocoton** [TheBobPony/getwindows11.tech#91]
I am interested in getting windows 11 but i'm not sure if it's legal, i asked my partner via message(he's on vacation), and i'm waiting an answer from him, also he's a lawyer so he knows things like this.

Thanks

**Comment by sysdotini** [comment]
Technically, yes it is legal. You are not breaking any NDA or even the Microsoft Consumer Agreement.

If you want to run an official Windows 11 build, wait until next week for the first Windows Insider builds to roll out. I would not recommend maining the leaked build as it is incomplete and missing the entire feature pack that unlocks a lot of the new UI elements.
