### ISSUE TITLE
[NEW] - Custom Mirror

### ISSUE THREAD

**Issue by ItsNeverLand** [TheBobPony/getwindows11.tech#94]
**URL**
https://neverland-windows11iso.gq/

**Type**
Normal 

**Notes**
Only includes warnings about how strict Microsoft is with this build.

**Comment by imrolii** [comment]
Webserver down as of now.

**Comment by NeverLandYT** [comment]
Temporarily down as I'm doing a emergency update to my VPS.
In an hour should be back up.

**Comment by NeverLandYT** [comment]
It should work now. Won't go down again.

**Comment by JivarMC** [comment]
ISO appears to be 2GB, kinda sketchy since normal ISOs are 4.5GB~

**Comment by imrolii** [comment]
Yeah, make sure the ISO isn't corrupt

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by NeverLandYT** [comment]
oh my god why is this annoying. reuploading it.

**Comment by NeverLandYT** [comment]
Issue is now resolved. It will now work.

**Comment by ItsNeverLand** [comment]
Closed due to remaking the issue.
