### ISSUE TITLE
[BROKEN] megaup.net

### ISSUE THREAD

**Issue by thepwrtank18** [TheBobPony/getwindows11.tech#98]
**Mirror**
Provide the troublesome mirror name (or URL).
https://megaup.net/1Dq24/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso
**Problem**
Is the mirror broken? DMCAd? Slow?
Requires adblock removed, removing it spams you with porn ads
**Notes**
Any notes you'd like us to have

**Comment by TheVisionRo-Dak** [comment]
ok, but the mirror isn't broken, If you're using the internet for more than 2 weeks you should know that you just shoudn't click the ads /shrug

**Comment by TheBobPony** [comment]
Mirror is still up, if you don't like the ads on the site... just use another mirror.
