### ISSUE TITLE
[BROKEN] moebox.pl

### ISSUE THREAD

**Issue by thepwrtank18** [TheBobPony/getwindows11.tech#99]
**Mirror**
Provide the troublesome mirror name (or URL).
https://moebox.pl/21996.1.210529-1541.co_release_CLIENT_CONSUMER_x64FRE_en-us.iso
**Problem**
Is the mirror broken? DMCAd? Slow?
Loads infinitely
**Notes**
Any notes you'd like us to have

**Comment by PolishNeko** [comment]
No

**Comment by TheBobPony** [comment]
Link still works, closing issue.
